# Generated by Django 4.2.1 on 2023-06-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderitem_author_product_author_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='book author', max_length=200, null=True),
        ),
    ]
